//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ID_Picker.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ID_Picker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1	Holzstock	1	0
        ///2	Holzknüppel	4	0
        ///3	Holzschwert	7	0
        ///4	Holzhammer	10	0
        ///5	Schwerer Holzhammer	13	0
        ///6	Holzschwert des Lehrlings	15	0
        ///7	Schwert des Abenteurers	18	0
        ///8	Holzschleuder	1	0
        ///9	Schwere Holzschleuder	6	0
        ///10	Holzschleuder des Lehrlings	12	0
        ///11	Schleuder des Abenteurers	16	0
        ///12	Kleidung	1	1
        ///13	Trainingsuniform	3	1
        ///14	Abenteurerkleidung	8	1
        ///15	Trainingsrüstung	11	1
        ///16	Mantelset des Reisenden	14	1
        ///17	Warmes Mantelset	17	1
        ///18	Anfängerschwert	15	0
        ///19	Kurzschwert	20	0
        ///20	Schwert des Leidens	26	0
        ///21	Kurzes Sch [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string DE_items {
            get {
                return ResourceManager.GetString("DE_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1	NosVille
        ///2	NosVille-Wiesen
        ///3	Minenprärie
        ///4	Sonnige Wiesen
        ///5	Fernonvorposten
        ///6	Westliche Mine 1
        ///7	Westliche Mine 2
        ///8	Nördliche Mine
        ///9	Westliche Mine 2
        ///10	Fernontempel 1
        ///11	Fernontempel U1
        ///12	Fernontempel U2
        ///13	Fernongruft 1
        ///14	Fernongruft 2
        ///15	Fernongruft 3
        ///16	Fernongruft 4
        ///17	Fernongruft 5
        ///20	Westlicher Krem
        ///21	Östlicher Krem
        ///22	Gipfel des Krem
        ///23	Berghöhle 1
        ///24	Berghöhle 2
        ///25	Berghöhle 3
        ///26	Berghöhle 4
        ///27	Berghöhle 5
        ///28	Berghöhle 6
        ///29	Shanera Dungeon -1
        ///30	Shanera Dungeon -2
        ///31	Shanera Dungeon -3
        ///32	Shan [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string DE_maps {
            get {
                return ResourceManager.GetString("DE_maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0	Kleiner Fuchs
        ///1	Fuchs
        ///2	Großer Fuchs
        ///3	Müder Dusifuchs
        ///4	Dusifuchs
        ///5	Nervöser Dusifuchs
        ///6	Glücklicher Otofuchs
        ///7	Otofuchs
        ///8	Wütender Otofuchs
        ///9	Glückliches Wollie
        ///10	Wollie
        ///11	Wütendes Wollie
        ///12	Kleiner Mufflon
        ///13	Mufflon
        ///14	Großer Mufflon
        ///15	Müder Widder
        ///16	Widder
        ///17	Nervöser Widder
        ///18	Glückliches Mandra
        ///19	Mandra
        ///20	Wütendes Mandra
        ///21	Schwaches Grasmandra
        ///22	Grasmandra
        ///23	Starkes Grasmandra
        ///24	Kleiner Dander
        ///25	Dander
        ///26	Großer Dander
        ///27	Schwacher Giftdander
        ///28	Giftdander
        ///29	Starker Giftdander
        ///30	Schwac [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string DE_monster {
            get {
                return ResourceManager.GetString("DE_monster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1	Wooden Stick	1	0
        ///2	Wooden Stick	4	0
        ///3	Wooden Sword	7	0
        ///4	Wooden Hammer	10	0
        ///5	Heavy Wooden Hammer	13	0
        ///6	Trainee&apos;s Wooden Sword	15	0
        ///7	Adventurer&apos;s Sword	18	0
        ///8	Wooden Catapult	1	0
        ///9	Heavy Wooden Catapult	6	0
        ///10	Trainee&apos;s Wooden Catapult	12	0
        ///11	Adventurer&apos;s Catapult	16	0
        ///12	Clothing	1	1
        ///13	Training Uniform	3	1
        ///14	Adventurer&apos;s Uniform	8	1
        ///15	Training Uniform	11	1
        ///16	Adventurer&apos;s Cloak Set	14	1
        ///17	Warm Cloak Set	17	1
        ///18	Beginner&apos;s Sword	15	0
        ///19	Short Sword	20	0
        ///20	Sword of Pain	26	0
        ///21	Short Sword	29	0
        ///22	 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string EN_items {
            get {
                return ResourceManager.GetString("EN_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1	NosVille
        ///2	NosVille Meadows
        ///3	Mine Plains
        ///4	Sunny Meadows
        ///5	Fernon Outpost
        ///6	Western Mine 1
        ///7	Western Mine 2
        ///8	Northern Mine
        ///9	Western Mine 2
        ///10	Fernon Temple 1
        ///11	Fernon Temple -1
        ///12	Fernon Temple -2
        ///13	Fernon&apos;s Hideout 1
        ///14	Fernon&apos;s Hideout 2
        ///15	Fernon&apos;s Hideout 3
        ///16	Fernon&apos;s Hideout 4
        ///17	Fernon&apos;s Hideout 5
        ///20	Western Krem
        ///21	Eastern Krem
        ///22	Peak of Mt. Krem
        ///23	Mountain Cave 1
        ///24	Mountain Cave 2
        ///25	Mountain Cave 3
        ///26	Mountain Cave 4
        ///27	Mountain Cave 5
        ///28	Mountain Cave 6
        ///29	Shanera Dungeon -1
        ///30	Shanera  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string EN_maps {
            get {
                return ResourceManager.GetString("EN_maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0	Baby Fox
        ///1	Fox
        ///2	Big Fox
        ///3	Tired Dusi-Fox
        ///4	Dusi-Fox
        ///5	Nervous Dusi-Fox
        ///6	Happy Oto-Fox
        ///7	Oto-Fox
        ///8	Angry Oto-Fox
        ///9	Happy Wooly
        ///10	Wooly
        ///11	Angry Wooly
        ///12	Small Mufflon
        ///13	Mufflon
        ///14	Big Mufflon
        ///15	Tired Ram
        ///16	Ram
        ///17	Nervous Ram
        ///18	Happy Mandra
        ///19	Mandra
        ///20	Angry Mandra
        ///21	Weak Grasmandra
        ///22	Grasmandra
        ///23	Strong Grasmandra
        ///24	Baby Dander
        ///25	Dander
        ///26	Large Dander
        ///27	Weak Toxi Dander
        ///28	Toxi Dander
        ///29	Strong Toxi Dander
        ///30	Weak Seedle
        ///31	Seedle
        ///32	Strong Seedle
        ///33	Light Fire Seedle
        ///34	Fire Seedle
        ///35	Heavy [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string EN_monster {
            get {
                return ResourceManager.GetString("EN_monster", resourceCulture);
            }
        }
    }
}
